


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_demo?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver